--- #YAML:1.0
name:               Term-Completion
version:            0.91
abstract:           read one line of user input, with convenience functions
author:
    - Marek Rouchal <marekr@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Handle:     0
    Term::ReadKey:  2.3
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
